# Generated by Django 4.2.23 on 2025-07-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_tags", models.TextField(blank=True)),
                ("content_code", models.TextField()),
                ("language", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("process_code", models.TextField()),
                ("process_application", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProcessFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formula_text", models.TextField()),
                (
                    "process_explanation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="web.processexplanation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable_name", models.CharField(max_length=100)),
                ("variable_unit", models.CharField(max_length=50)),
                ("variable_mean_en", models.CharField(max_length=50)),
                ("variable_mean_zh", models.CharField(max_length=50)),
                (
                    "process_formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="web.processformula",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="web.datatype",
                    ),
                ),
            ],
            options={
                "unique_together": {("type", "value")},
            },
        ),
        migrations.CreateModel(
            name="DataItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tags", models.ManyToManyField(to="web.datavalue")),
            ],
        ),
    ]
